---
# Note: indendentation is important
# Verify formatting here: https://yaml-online-parser.appspot.com/

# Global settings, applying to the web server
global:
  web_port: 8080
  webhook_secret: 'Secret'
  flask_debug: True
  db_server: 'DBServer'
  db_name: 'DBName'


# Enabled plugins
plugins:
  mist:
    name: 'Mist Webhooks'
    route: 'mist'
    class: MistHandler
    module: plugins.mist.misthandler
  junos:
    name: 'Junos Webhooks'
    route: 'junos'
    class: JunosHandler
    module: plugins.junos.junos


# MS Graph API settings
graph:
  base_url: 'https://graph.microsoft.com/v1.0/'
  user_id: 'xxxxxxxx-xxxx-xxxx-xxxx-xxxxxxxxxxxx'
  chat_id: '19:847516a419864851b24cb9f7e8a6426b@thread.v2'


# SMTP server settings
smtp:
  server: 'mail.server.com'
  port: 25
  sender: 'user@server.com'
  receivers:
    - 'user@server.com'
    - 'user2@server.com'
