---
# Note: indendentation is important
# Verify formatting here: https://yaml-online-parser.appspot.com/

# Global settings, applying to the web server
global:
  web_port: 8080
  webhook_secret: 'password'
  flask_debug: False
  db_server: 'DB-Server'
  db_name: 'DB-Name'
  chatbot_name: 'Steve'


# Enabled plugins
plugins:
  mist:
    name: 'Mist Webhooks'
    route: 'mist'
    class: MistHandler
    module: plugins.mist.misthandler
  junos:
    name: 'Junos Webhooks'
    route: 'junos'
    class: JunosHandler
    module: plugins.junos.junos
  loginsight:
    name: 'Log Insight'
    route: 'loginsight'
    class: LogInsight
    module: plugins.loginsight.log_insight


# MS Graph API settings
graph:
  base_url: 'https://graph.microsoft.com/v1.0/'
  chat_id: '19:xxxx@thread.v2'
  key_id: '123'
  chat_url: 'https://my_domain.com/chat'


# MS Teams Settings
teams:
  app_id: 'xxxx'
  secret: 'xxxx'
  tenant: 'xxxx'
  user: 'user@my_domain.com'


# SMTP server settings
smtp:
  server: 'smtp.my_domain.com'
  port: 25
  sender: 'user@my_domain.com'
  receivers:
    - 'user@my_domain.com'
