---
# Note: indendentation is important
# Verify formatting here: https://yaml-online-parser.appspot.com/

# Global settings, applying to the web server
global:
  web_port: 8080
  webhook_secret: 'Secret'
  flask_debug: True
  db_server: 'My_Server'
  db_name: 'My_DB'


# Enabled plugins
plugins:
  mist:
    name: 'Mist Webhooks'
    route: 'mist'
    class: MistHandler
    module: plugins.mist.misthandler
  junos:
    name: 'Junos Webhooks'
    route: 'junos'
    class: JunosHandler
    module: plugins.junos.junos
  loginsight:
    name: 'Log Insight'
    route: 'loginsight'
    class: LogInsight
    module: plugins.loginsight.log_insight


# MS Graph API settings
graph:
  base_url: 'https://graph.microsoft.com/v1.0/'
  user_id: 'xxxxxx-xxxx-xxxx-xxxx-xxxxxxxxxxxx'
  chat_id: '19:xxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxx@thread.v2'


# MS Teams Settings
teams:
  app_id: 'xxxxxx-xxxx-xxxx-xxxx-xxxxxxxxxxxx'
  secret: 'xxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxx'
  tenant: 'xxxxxx-xxxx-xxxx-xxxx-xxxxxxxxxxxx'


# SMTP server settings
smtp:
  server: 'my_smtp_server'
  port: 25
  sender: 'my@email.com'
  receivers:
    - 'my@email.com'
    - 'your@email.com'
